### PR TITLE
only Main process tries to set state

### LINKED ISSUE #27: bad file descriptor errors
I keep getting errors, `Uncaught Error: EBADF: bad file descriptor, close`, that point back to the `setState` function in PersistedState.

I wonder if this happens when multiple mutations happen in quick succession. Is there a known limitation in this sense? Is so, might it be possible to implement some kind of debounce to prevent file issues?

### PR DESCRIPTION
**Pull request by michaeljpeake**
My testing (on Windows only) has found frequent file errors caused by one or more renderers trying to write the store state to disk at the same time as the main process.

The if statement I have added prevents processes of type `renderer` from duplicating the work of the main process.

Fixes #27

### CODE REVIEW

**Comment by Bomberus** [comment]
Short question, why do you check for: process.env.NODE_ENV === "test" ?
Will this be false, once I deploy my electron app?

**Comment by michaeljpeake** [comment]
> 
> 
> Short question, why do you check for: process.env.NODE_ENV === "test" ?
> Will this be false, once I deploy my electron app?

This is to allow the tests to run, as they do not create an Electron browser (main) process.

**Comment by Bomberus** [comment]
Thanks, good to know.

**Comment by MrEmelianenko** [comment]
https://github.com/vue-electron/vuex-electron/issues/44

**Comment by michaeljpeake** [comment]
Closing as years old now.

**Pull request closed without merging**
